version: '3'

tasks:
  # 進行程式碼檢查
  lint:
    ignore_error: true
    cmds:
      - task: install
      - task: fmt-mizugo
      - task: fmt-client-unity
      - task: fmt-client-unity-sample
      - task: fmt-proto
      - task: lint-mizugo

  # mizugo程式碼格式化
  fmt-mizugo:
    cmds:
      - gofmt -s -w -l .

  # client-unity格式化
  fmt-client-unity:
    dir: support/client-unity/Packages/com.fouridstudio.mizugo-client-unity
    cmds:
      - dotnet csharpier .

  # client-unity-sample格式化
  fmt-client-unity-sample:
    dir: support/test-client-cs/Assets/Scripts
    cmds:
      - dotnet csharpier .

  # proto格式化
  fmt-proto:
    dir: support/proto
    cmds:
      - buf format -w .
      - dotnet csharpier .

  # mizugo程式碼檢查
  lint-mizugo:
    cmds:
      - golangci-lint -v run

  # 產生proto message
  proto:
    cmds:
      - task: proto-mizugo
      - task: proto-test

  # mizugo的proto轉換
  proto-mizugo:
    dir: support\proto\mizugo
    cmds:
      - cmd /C build.bat

  # 測試訊息的proto轉換
  proto-test:
    dir: support\proto\test
    cmds:
      - cmd /C build.bat

  # 進行程式碼測試
  test:
    cmds:
      - go test ./... -cover

  # 進行效能測試
  bench:
    cmds:
      - go test ./... -bench=. -benchmem

  # 更新子專案分支
  subtree:
    cmds:
      - git subtree split --prefix support/client-unity/Packages/com.fouridstudio.mizugo-client-unity --branch client-unity
      - git subtree split --prefix support/test-client-cs --branch client-unity-sample
      - git subtree split --prefix support/client-unity/Packages/com.fouridstudio.mizugo-proto-unity --branch proto-unity

  # 安裝工具
  install:
    ignore_error: true
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest # 安裝lint
      - dotnet tool install csharpier -g # 安裝cs格式化工具
      - go install github.com/bufbuild/buf/cmd/buf@latest # 安裝proto格式化工具