version: '3'

tasks:
  # 進行程式碼檢查
  lint:
    ignore_error: true
    cmds:
      - task: install
      - task: fmt-mizugo
      - task: fmt-client-unity
      - task: fmt-client-unity-sample
      - task: fmt-proto
      - task: lint-mizugo

  fmt-mizugo:
    cmds:
      - gofmt -s -w -l .

  fmt-client-unity:
    dir: support/client-unity/Packages/com.fouridstudio.mizugo-client-unity
    cmds:
      - dotnet csharpier .

  fmt-client-unity-sample:
    dir: support/test-client-cs/Assets/Scripts
    cmds:
      - dotnet csharpier .

  fmt-proto:
    dir: support/proto
    cmds:
      - buf format -w .
      - dotnet csharpier .

  lint-mizugo:
    cmds:
      - golangci-lint -v run

  # 進行單元測試
  test:
    cmds:
      - go test ./... -cover

  # 進行效能測試
  bench:
    cmds:
      - go test ./... -bench=. -benchmem

  # 更新訊息
  proto:
    cmds:
      - task: proto-mizugo
      - task: proto-test

  proto-mizugo:
    dir: support\proto\mizugo
    cmds:
      - cmd /C build.bat

  proto-test:
    dir: support\proto\test
    cmds:
      - cmd /C build.bat

  # 更新子專案分支
  subtree:
    cmds:
      - git subtree split --prefix support/client-unity/Packages/com.fouridstudio.mizugo-proto-unity --branch proto-unity
      - git subtree split --prefix support/client-unity/Packages/com.fouridstudio.mizugo-client-unity --branch client-unity
      - git subtree split --prefix support/test-client-cs --branch client-unity-sample

  # 停止容器
  stop:
    cmds:
      - docker stop $(docker ps -q)

  # 啟動資料庫
  db:
    cmds:
      # 檢查網路是否存在, 不然就建立它
      - |
        if ! docker network ls | grep -qw dev; then
          docker network create dev
        fi
      # 啟動redis
      - docker build -t dbredis -f docker/docker-redis .
      - docker rm -f -v dbredis || true
      - docker volume rm dbredis-volume || true
      - docker run -d --name dbredis --network dev -v dbredis-volume:/data -p 6379:6379 dbredis redis-server /usr/local/etc/redis/redis.conf
      # 啟動mongo
      - docker pull mongo:latest
      - docker rm -f -v dbmongo
      - docker volume rm dbmongo-volume || true
      - docker run -d --name dbmongo --network dev -v dbmongo-volume:/data/db -p 27017:27017 mongo:latest
      # 清除懸空鏡像
      - docker image prune -f

  # 安裝工具
  install:
    ignore_error: true
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest # 安裝lint
      - dotnet tool install csharpier -g # 安裝cs格式化工具
      - go install github.com/bufbuild/buf/cmd/buf@latest # 安裝proto格式化工具