version: '3'

tasks:
  # 進行程式碼檢查
  lint:
    ignore_error: true
    cmds:
      - task: install
      - task: fmt-mizugo
      - task: fmt-client-unity
      - task: fmt-client-unity-sample
      - task: fmt-proto
      - task: lint-mizugo

  fmt-mizugo:
    cmds:
      - gofmt -s -w -l .

  fmt-client-unity:
    dir: support/client-unity/Packages/com.fouridstudio.mizugo-client-unity
    cmds:
      - dotnet csharpier .

  fmt-client-unity-sample:
    dir: support/test-client-cs/Assets/Scripts
    cmds:
      - dotnet csharpier .

  fmt-proto:
    dir: support/proto
    cmds:
      - buf format -w .
      - dotnet csharpier .

  lint-mizugo:
    cmds:
      - golangci-lint -v run

  # 產生proto message
  proto:
    cmds:
      - task: proto-mizugo
      - task: proto-test

  proto-mizugo:
    dir: support\proto\mizugo
    cmds:
      - cmd /C build.bat

  proto-test:
    dir: support\proto\test
    cmds:
      - cmd /C build.bat

  # 進行程式碼測試
  test:
    cmds:
      - go test ./... -cover

  # 進行效能測試
  bench:
    cmds:
      - go test ./... -bench=. -benchmem

  # 更新子專案分支
  subtree:
    cmds:
      - git subtree split --prefix support/client-unity/Packages/com.fouridstudio.mizugo-proto-unity --branch proto-unity
      - git subtree split --prefix support/client-unity/Packages/com.fouridstudio.mizugo-client-unity --branch client-unity
      - git subtree split --prefix support/test-client-cs --branch client-unity-sample

  # 在docker上啟動資料庫
  db:
    cmds:
      - task: dbredis
      - task: dbmongo

  dbredis:
    cmds:
      - docker pull redis:latest
      - docker rm -f -v mizugo-redis
      - docker volume rm mizugo-redis-volume || true
      - docker run -d --name mizugo-redis -v mizugo-redis-volume:/data -p 6379:6379 redis:latest redis-server

  dbmongo:
    cmds:
      - docker pull mongo:latest
      - docker rm -f -v mizugo-mongo
      - docker volume rm mizugo-mongo-volume || true
      - docker run -d --name mizugo-mongo -v mizugo-mongo-volume:/data/db -p 27017:27017 mongo:latest

  # 安裝工具
  install:
    ignore_error: true
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest # 安裝lint
      - dotnet tool install csharpier -g # 安裝cs格式化工具
      - go install github.com/bufbuild/buf/cmd/buf@latest # 安裝proto格式化工具