version: '3'

tasks:
  # 進行程式碼檢查
  lint:
    cmds:
      - task: fmt-mizugo
      - task: fmt-client-unity
      - task: fmt-client-unity-sample
      - task: fmt-proto
      - task: fmt-proto-cs
      - task: lint-mizugo

  # 進行程式碼測試
  test:
    cmds:
      - go test ./... -cover

  # 進行效能測試
  bench:
    cmds:
      - go test ./... -bench=. -benchmem

  # 進行proto轉換
  proto:
    cmds:
      - task: proto-mizugo
      - task: proto-test

  # 更新客戶端組件分支
  clientunity:
    cmds:
      - git subtree split --prefix=support/client-unity/Packages/com.fouridstudio.mizugo-client-unity --branch clientunity
      - git subtree split --prefix=support/test-client-cs --branch clientunity-sample

  # mizugo的proto轉換
  proto-mizugo:
    dir: support\proto\mizugo
    cmds:
      - build.bat

  # 測試訊息的proto轉換
  proto-test:
    dir: support\proto\test
    cmds:
      - build.bat

  # mizugo程式碼格式化
  fmt-mizugo:
    cmds:
      - gofmt -s -w -l .

  # client-unity格式化
  fmt-client-unity:
    dir: support/client-unity/Packages/com.fouridstudio.mizugo-client-unity
    cmds:
      - dotnet csharpier .
      
  # client-unity-sample格式化
  fmt-client-unity-sample:
    dir: support/test-client-cs/Assets/Scripts
    cmds:
      - dotnet csharpier .

  # proto格式化
  fmt-proto:
    cmds:
      - go install github.com/bufbuild/buf/cmd/buf@latest
      - buf format -w .

  # proto-cs訊息格式化
  fmt-proto-cs:
    dir: support/proto
    cmds:
      - dotnet csharpier .

  # mizugo程式碼檢查
  lint-mizugo:
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - golangci-lint -v run